"""Фразы услуг: именительный запрос, винительный для FAQ, родительный для цены."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Phrase:
    query: str
    faq_about: str
    price_of: str
    copy_id: str
    faq_id: str
    topic: str = ""


def _p(query: str, faq_about: str, price_of: str, copy_id: str, faq_id: str, topic: str = "") -> Phrase:
    return Phrase(query, faq_about, price_of, copy_id, faq_id, topic)


PHRASES: dict[str, Phrase] = {
    "/uslugi/": _p("Услуги клиники", "услуги клиники", "услуг клиники", "catalog", "catalog"),
    "/uslugi/narkologicheskaya-pomosh/": _p("Наркологическая помощь", "наркологическую помощь", "наркологической помощи", "narcology_help", "treatment"),
    "/uslugi/narkologicheskaya-pomosh/konsultaciya-narkologa/": _p("Консультация нарколога", "консультацию нарколога", "консультации нарколога", "consult", "consult"),
    "/uslugi/narkologicheskaya-pomosh/psihiatr-narkolog/": _p("Приём психиатра-нарколога", "приём психиатра-нарколога", "приёма психиатра-нарколога", "consult", "consult"),
    "/uslugi/narkologicheskaya-pomosh/onlajn-konsultaciya/": _p("Онлайн-консультация психиатра-нарколога", "онлайн-консультацию психиатра-нарколога", "онлайн-консультации психиатра-нарколога", "online", "online"),
    "/uslugi/narkologicheskaya-pomosh/stacionar/": _p("Наркологический стационар", "наркологический стационар", "размещения в наркологическом стационаре", "inpatient", "inpatient"),
    "/uslugi/narkologicheskaya-pomosh/gospitalizaciya/": _p("Госпитализация в стационар", "госпитализацию", "госпитализации", "inpatient", "inpatient"),
    "/uslugi/narkologicheskaya-pomosh/chastnyj-vytrezvitel/": _p("Частный вытрезвитель", "частный вытрезвитель", "пребывания в вытрезвителе", "vytrezvitel", "vytrezvitel"),
    "/uslugi/narkologicheskaya-pomosh/srochnaya-pomosh/": _p("Срочная наркологическая помощь", "срочную наркологическую помощь", "срочной наркологической помощи", "urgent", "urgent"),
    "/uslugi/narkolog-na-dom/": _p("Нарколог на дом", "вызов нарколога на дом", "вызова нарколога на дом", "home_doctor", "home"),
    "/uslugi/vyvod-iz-zapoya/": _p("Вывод из запоя", "вывод из запоя", "помощи при запое", "home_withdrawal", "withdrawal"),
    "/uslugi/vyvod-iz-zapoya/na-domu/": _p("Вывод из запоя на дому", "вывод из запоя на дому", "вывода из запоя на дому", "home_withdrawal", "withdrawal"),
    "/uslugi/vyvod-iz-zapoya/v-stacionare/": _p("Вывод из запоя в стационаре", "вывод из запоя в стационаре", "вывода из запоя в стационаре", "inpatient", "inpatient"),
    "/uslugi/kapelnitsy/": _p("Капельницы и детокс", "капельницы и детокс", "капельницы и детокса", "home_drip", "drip"),
    "/uslugi/kapelnitsy/ot-zapoya-i-alkogolya/": _p("Капельница от запоя", "капельницу от запоя", "капельницы от запоя", "home_drip", "drip"),
    "/uslugi/kapelnitsy/ot-pohmelya/": _p("Капельница от похмелья", "капельницу от похмелья", "капельницы от похмелья", "home_drip", "drip"),
    "/uslugi/kapelnitsy/detoksikaciya/": _p("Алкогольная детоксикация", "алкогольную детоксикацию", "алкогольной детоксикации", "home_drip", "drip"),
    "/uslugi/kapelnitsy/alkogolnaya-intoksikaciya/": _p("Помощь при алкогольной интоксикации", "помощь при алкогольной интоксикации", "помощи при алкогольной интоксикации", "home_drip", "drip"),
    "/uslugi/kapelnitsy/abstinentnyj-sindrom/": _p("Помощь при абстинентном синдроме", "помощь при абстинентном синдроме", "помощи при абстинентном синдроме", "withdrawal_care", "withdrawal_care"),
    "/uslugi/kodirovanie/": _p("Кодирование от алкоголизма", "кодирование от алкоголизма", "кодирования от алкоголизма", "coding", "coding"),
    "/uslugi/kodirovanie/na-domu/": _p("Кодирование на дому", "кодирование на дому", "кодирования на дому", "coding_home", "coding"),
    "/uslugi/kodirovanie/v-klinike/": _p("Кодирование в клинике", "кодирование в клинике", "кодирования в клинике", "coding", "coding"),
    "/uslugi/kodirovanie/medikamentoznoe/": _p("Медикаментозное кодирование", "медикаментозное кодирование", "медикаментозного кодирования", "coding", "coding"),
    "/uslugi/kodirovanie/metod-dovzhenko/": _p("Кодирование по методу Довженко", "кодирование по методу Довженко", "кодирования по методу Довженко", "coding", "coding"),
    "/uslugi/kodirovanie/gipnoz/": _p("Кодирование гипнозом", "кодирование гипнозом", "кодирования гипнозом", "coding", "coding"),
    "/uslugi/kodirovanie/ukol/": _p("Кодирование уколом", "кодирование уколом", "кодирования уколом", "coding", "coding"),
    "/uslugi/kodirovanie/vshivanie/": _p("Вшивание от алкоголизма", "вшивание от алкоголизма", "вшивания от алкоголизма", "coding", "coding"),
    "/uslugi/kodirovanie/dvojnoj-blok/": _p("Кодирование двойным блоком", "кодирование двойным блоком", "кодирования двойным блоком", "coding", "coding"),
    "/uslugi/kodirovanie/s-provokaciej/": _p("Кодирование с провокацией", "кодирование с провокацией", "кодирования с провокацией", "coding", "coding"),
    "/uslugi/kodirovanie/preparaty/": _p("Препараты для кодирования", "препараты для кодирования", "препаратов для кодирования", "coding", "coding"),
    "/uslugi/kodirovanie/preparaty/esperal/": _p("Кодирование Эспераль", "кодирование Эспераль", "кодирования Эспераль", "brand", "brand", "Эспераль"),
    "/uslugi/kodirovanie/preparaty/akvilong/": _p("Кодирование Аквилонг", "кодирование Аквилонг", "кодирования Аквилонг", "brand", "brand", "Аквилонг"),
    "/uslugi/kodirovanie/preparaty/algominal/": _p("Кодирование Алгоминал", "кодирование Алгоминал", "кодирования Алгоминал", "brand", "brand", "Алгоминал"),
    "/uslugi/kodirovanie/preparaty/disulfiram/": _p("Кодирование дисульфирамом", "кодирование дисульфирамом", "кодирования дисульфирамом", "brand", "brand", "дисульфирам"),
    "/uslugi/kodirovanie/preparaty/naltrekson/": _p("Кодирование налтрексоном", "кодирование налтрексоном", "кодирования налтрексоном", "brand", "brand", "налтрексон"),
    "/uslugi/kodirovanie/preparaty/vivitrol/": _p("Кодирование Вивитрол", "кодирование Вивитрол", "кодирования Вивитрол", "brand", "brand", "Вивитрол"),
    "/uslugi/kodirovanie/preparaty/torpedo/": _p("Кодирование Торпедо", "кодирование Торпедо", "кодирования Торпедо", "brand", "brand", "Торпедо"),
    "/uslugi/kodirovanie/raskodirovanie/": _p("Раскодирование", "раскодирование", "раскодирования", "uncode", "uncode"),
    "/uslugi/kodirovanie/raskodirovanie/esperal/": _p("Раскодирование от Эспераль", "раскодирование от Эспераль", "раскодирования от Эспераль", "uncode", "uncode", "Эспераль"),
    "/uslugi/kodirovanie/raskodirovanie/akvilong/": _p("Раскодирование от Аквилонг", "раскодирование от Аквилонг", "раскодирования от Аквилонг", "uncode", "uncode", "Аквилонг"),
    "/uslugi/kodirovanie/raskodirovanie/algominal/": _p("Раскодирование от Алгоминал", "раскодирование от Алгоминал", "раскодирования от Алгоминал", "uncode", "uncode", "Алгоминал"),
    "/uslugi/kodirovanie/raskodirovanie/disulfiram/": _p("Раскодирование от дисульфирама", "раскодирование от дисульфирама", "раскодирования от дисульфирама", "uncode", "uncode", "дисульфирам"),
    "/uslugi/kodirovanie/raskodirovanie/naltrekson/": _p("Раскодирование от налтрексона", "раскодирование от налтрексона", "раскодирования от налтрексона", "uncode", "uncode", "налтрексон"),
    "/uslugi/kodirovanie/raskodirovanie/vivitrol/": _p("Раскодирование от Вивитрол", "раскодирование от Вивитрол", "раскодирования от Вивитрол", "uncode", "uncode", "Вивитрол"),
    "/uslugi/kodirovanie/raskodirovanie/torpedo/": _p("Раскодирование от Торпедо", "раскодирование от Торпедо", "раскодирования от Торпедо", "uncode", "uncode", "Торпедо"),
    "/uslugi/lechenie-alkogolizma/": _p("Лечение алкоголизма", "лечение алкоголизма", "лечения алкоголизма", "alcoholism", "treatment"),
    "/uslugi/lechenie-alkogolizma/na-domu/": _p("Лечение алкоголизма на дому", "лечение алкоголизма на дому", "лечения алкоголизма на дому", "home_doctor", "home"),
    "/uslugi/lechenie-alkogolizma/v-stacionare/": _p("Лечение алкоголизма в стационаре", "лечение алкоголизма в стационаре", "лечения алкоголизма в стационаре", "inpatient", "inpatient"),
    "/uslugi/lechenie-alkogolizma/ambulatorno/": _p("Амбулаторное лечение алкоголизма", "амбулаторное лечение алкоголизма", "амбулаторного лечения алкоголизма", "alcoholism", "treatment"),
    "/uslugi/lechenie-alkogolizma/zhenskij-alkogolizm/": _p("Лечение женского алкоголизма", "лечение женского алкоголизма", "лечения женского алкоголизма", "alcohol_topic", "alcohol_topic", "женском алкоголизме"),
    "/uslugi/lechenie-alkogolizma/muzhskoj-alkogolizm/": _p("Лечение мужского алкоголизма", "лечение мужского алкоголизма", "лечения мужского алкоголизма", "alcohol_topic", "alcohol_topic", "мужском алкоголизме"),
    "/uslugi/lechenie-alkogolizma/pivnoj-alkogolizm/": _p("Лечение пивного алкоголизма", "лечение пивного алкоголизма", "лечения пивного алкоголизма", "alcohol_topic", "alcohol_topic", "пивном алкоголизме"),
    "/uslugi/lechenie-alkogolizma/hronicheskij-alkogolizm/": _p("Лечение хронического алкоголизма", "лечение хронического алкоголизма", "лечения хронического алкоголизма", "alcohol_topic", "alcohol_topic", "хроническом алкоголизме"),
    "/uslugi/lechenie-alkogolizma/u-pozhilyh/": _p("Лечение алкоголизма у пожилых", "лечение алкоголизма у пожилых", "лечения алкоголизма у пожилых", "alcohol_topic", "alcohol_topic", "алкоголизме у пожилых"),
    "/uslugi/lechenie-alkogolizma/bez-kodirovaniya/": _p("Лечение алкоголизма без кодирования", "лечение алкоголизма без кодирования", "лечения алкоголизма без кодирования", "alcoholism", "treatment"),
    "/uslugi/lechenie-alkogolizma/podrostkovyj/": _p("Лечение подросткового алкоголизма", "лечение подросткового алкоголизма", "лечения подросткового алкоголизма", "alcohol_topic", "alcohol_topic", "подростковом алкоголизме"),
    "/uslugi/lechenie-alkogolizma/alkogolnyj-delirij/": _p("Помощь при алкогольном делирии", "помощь при алкогольном делирии", "помощи при алкогольном делирии", "delirium", "delirium"),
    "/uslugi/snyatie-lomki/": _p("Снятие ломки", "снятие ломки", "снятия ломки", "withdrawal_care", "withdrawal_care"),
    "/uslugi/snyatie-lomki/na-domu/": _p("Снятие ломки на дому", "снятие ломки на дому", "снятия ломки на дому", "withdrawal_care", "withdrawal_care"),
    "/uslugi/snyatie-lomki/v-stacionare/": _p("Снятие ломки в стационаре", "снятие ломки в стационаре", "снятия ломки в стационаре", "inpatient", "inpatient"),
    "/uslugi/lechenie-narkomanii/": _p("Лечение наркомании", "лечение наркомании", "лечения наркомании", "treatment", "treatment"),
    "/uslugi/lechenie-narkomanii/v-stacionare/": _p("Лечение наркомании в стационаре", "лечение наркомании в стационаре", "лечения наркомании в стационаре", "inpatient", "inpatient"),
    "/uslugi/lechenie-narkomanii/na-domu/": _p("Лечение наркомании на дому", "лечение наркомании на дому", "лечения наркомании на дому", "home_doctor", "home"),
    "/uslugi/lechenie-narkomanii/ambulatorno/": _p("Амбулаторное лечение наркомании", "амбулаторное лечение наркомании", "амбулаторного лечения наркомании", "treatment", "treatment"),
    "/uslugi/lechenie-narkomanii/medikamentoznoe/": _p("Медикаментозное лечение наркомании", "медикаментозное лечение наркомании", "медикаментозного лечения наркомании", "treatment", "treatment"),
    "/uslugi/lechenie-narkomanii/detoksikaciya/": _p("Детоксикация от наркотиков", "детоксикацию от наркотиков", "детоксикации от наркотиков", "withdrawal_care", "withdrawal_care"),
    "/uslugi/lechenie-narkomanii/detoksikaciya/ubod/": _p("Ультрабыстрая опиоидная детоксикация", "ультрабыструю опиоидную детоксикацию", "ультрабыстрой опиоидной детоксикации", "ubod", "ubod"),
    "/uslugi/lechenie-narkomanii/detoksikaciya/kapelnica/": _p("Капельница при наркотической интоксикации", "капельницу при наркотической интоксикации", "капельницы при наркотической интоксикации", "home_drip", "drip"),
    "/uslugi/lechenie-narkomanii/geroin/": _p("Лечение героиновой зависимости", "лечение героиновой зависимости", "лечения героиновой зависимости", "substance", "substance", "героиновой зависимости"),
    "/uslugi/lechenie-narkomanii/metadon/": _p("Лечение метадоновой зависимости", "лечение метадоновой зависимости", "лечения метадоновой зависимости", "substance", "substance", "метадоновой зависимости"),
    "/uslugi/lechenie-narkomanii/mefedron/": _p("Лечение мефедроновой зависимости", "лечение мефедроновой зависимости", "лечения мефедроновой зависимости", "substance", "substance", "мефедроновой зависимости"),
    "/uslugi/lechenie-narkomanii/kokain/": _p("Лечение кокаиновой зависимости", "лечение кокаиновой зависимости", "лечения кокаиновой зависимости", "substance", "substance", "кокаиновой зависимости"),
    "/uslugi/lechenie-narkomanii/amfetamin/": _p("Лечение амфетаминовой зависимости", "лечение амфетаминовой зависимости", "лечения амфетаминовой зависимости", "substance", "substance", "амфетаминовой зависимости"),
    "/uslugi/lechenie-narkomanii/metamfetamin/": _p("Лечение метамфетаминовой зависимости", "лечение метамфетаминовой зависимости", "лечения метамфетаминовой зависимости", "substance", "substance", "метамфетаминовой зависимости"),
    "/uslugi/lechenie-narkomanii/spajs/": _p("Лечение зависимости от спайса", "лечение зависимости от спайса", "лечения зависимости от спайса", "substance", "substance", "зависимости от спайса"),
    "/uslugi/lechenie-narkomanii/gashish/": _p("Лечение зависимости от гашиша", "лечение зависимости от гашиша", "лечения зависимости от гашиша", "substance", "substance", "зависимости от гашиша"),
    "/uslugi/lechenie-narkomanii/marihuana/": _p("Лечение зависимости от марихуаны", "лечение зависимости от марихуаны", "лечения зависимости от марихуаны", "substance", "substance", "зависимости от марихуаны"),
    "/uslugi/lechenie-narkomanii/soli/": _p("Лечение зависимости от солей", "лечение зависимости от солей", "лечения зависимости от солей", "substance", "substance", "зависимости от солей"),
    "/uslugi/lechenie-narkomanii/alfa-pvp/": _p("Лечение зависимости от альфа-PVP", "лечение зависимости от альфа-PVP", "лечения зависимости от альфа-PVP", "substance", "substance", "зависимости от альфа-PVP"),
    "/uslugi/lechenie-narkomanii/butirat/": _p("Лечение зависимости от бутирата", "лечение зависимости от бутирата", "лечения зависимости от бутирата", "substance", "substance", "зависимости от бутирата"),
    "/uslugi/drugie-zavisimosti/": _p("Лечение других зависимостей", "лечение других зависимостей", "лечения других зависимостей", "treatment", "treatment"),
    "/uslugi/drugie-zavisimosti/igromaniya/": _p("Помощь при игромании", "помощь при игромании", "помощи при игромании", "behavior", "behavior", "игромании"),
    "/uslugi/drugie-zavisimosti/stavki/": _p("Помощь при зависимости от ставок", "помощь при зависимости от ставок", "помощи при зависимости от ставок", "behavior", "behavior", "зависимости от ставок"),
    "/uslugi/drugie-zavisimosti/kompyuternaya/": _p("Помощь при компьютерной зависимости", "помощь при компьютерной зависимости", "помощи при компьютерной зависимости", "behavior", "behavior", "компьютерной зависимости"),
    "/uslugi/drugie-zavisimosti/internet/": _p("Помощь при интернет-зависимости", "помощь при интернет-зависимости", "помощи при интернет-зависимости", "behavior", "behavior", "интернет-зависимости"),
    "/uslugi/drugie-zavisimosti/nikotinovaya/": _p("Помощь при никотиновой зависимости", "помощь при никотиновой зависимости", "помощи при никотиновой зависимости", "behavior", "behavior", "никотиновой зависимости"),
    "/uslugi/drugie-zavisimosti/toksikomaniya/": _p("Помощь при токсикомании", "помощь при токсикомании", "помощи при токсикомании", "substance", "substance", "токсикомании"),
    "/uslugi/drugie-zavisimosti/lekarstvennaya/": _p("Лечение лекарственной зависимости", "лечение лекарственной зависимости", "лечения лекарственной зависимости", "substance", "substance", "лекарственной зависимости"),
    "/uslugi/drugie-zavisimosti/lekarstvennaya/pregabalin/": _p("Лечение зависимости от прегабалина", "лечение зависимости от прегабалина", "лечения зависимости от прегабалина", "substance", "substance", "зависимости от прегабалина"),
    "/uslugi/drugie-zavisimosti/lekarstvennaya/benzodiazepiny/": _p("Лечение зависимости от бензодиазепинов", "лечение зависимости от бензодиазепинов", "лечения зависимости от бензодиазепинов", "substance", "substance", "зависимости от бензодиазепинов"),
    "/uslugi/drugie-zavisimosti/lekarstvennaya/fenazepam/": _p("Лечение зависимости от феназепама", "лечение зависимости от феназепама", "лечения зависимости от феназепама", "substance", "substance", "зависимости от феназепама"),
    "/uslugi/drugie-zavisimosti/lekarstvennaya/tramadol/": _p("Лечение зависимости от трамадола", "лечение зависимости от трамадола", "лечения зависимости от трамадола", "substance", "substance", "зависимости от трамадола"),
    "/uslugi/drugie-zavisimosti/lekarstvennaya/kodein/": _p("Лечение зависимости от кодеина", "лечение зависимости от кодеина", "лечения зависимости от кодеина", "substance", "substance", "зависимости от кодеина"),
    "/uslugi/drugie-zavisimosti/lekarstvennaya/gabapentin/": _p("Лечение зависимости от габапентина", "лечение зависимости от габапентина", "лечения зависимости от габапентина", "substance", "substance", "зависимости от габапентина"),
    "/uslugi/drugie-zavisimosti/lekarstvennaya/antidepressanty/": _p("Сопровождение отмены антидепрессантов", "сопровождение отмены антидепрессантов", "сопровождения отмены антидепрессантов", "substance", "substance", "отмене антидепрессантов"),
    "/uslugi/reabilitaciya/": _p("Реабилитация зависимых", "реабилитацию зависимых", "реабилитации зависимых", "rehab", "rehab"),
    "/uslugi/reabilitaciya/alkogolizm/": _p("Реабилитация при алкоголизме", "реабилитацию при алкоголизме", "реабилитации при алкоголизме", "rehab_topic", "rehab_topic", "алкоголизме"),
    "/uslugi/reabilitaciya/narkomaniya/": _p("Реабилитация при наркомании", "реабилитацию при наркомании", "реабилитации при наркомании", "rehab_topic", "rehab_topic", "наркомании"),
    "/uslugi/reabilitaciya/igromaniya/": _p("Реабилитация при игромании", "реабилитацию при игромании", "реабилитации при игромании", "rehab_topic", "rehab_topic", "игромании"),
    "/uslugi/reabilitaciya/12-shagov/": _p("Программа «12 шагов»", "программу «12 шагов»", "программы «12 шагов»", "rehab", "rehab"),
    "/uslugi/reabilitaciya/resocializaciya/": _p("Ресоциализация зависимых", "ресоциализацию зависимых", "ресоциализации зависимых", "rehab", "rehab"),
    "/uslugi/psihiatriya/": _p("Психиатрическая помощь", "психиатрическую помощь", "психиатрической помощи", "clinic", "psych"),
    "/uslugi/psihiatriya/konsultaciya/": _p("Консультация психиатра", "консультацию психиатра", "консультации психиатра", "consult", "psych"),
    "/uslugi/psihiatriya/psihiatr-na-dom/": _p("Психиатр на дом", "выезд психиатра на дом", "выезда психиатра на дом", "home_psych", "psych_home"),
    "/uslugi/psihiatriya/onlajn/": _p("Онлайн-консультация психиатра", "онлайн-консультацию психиатра", "онлайн-консультации психиатра", "online", "online"),
    "/uslugi/psihiatriya/stacionar/": _p("Психиатрический стационар", "психиатрический стационар", "размещения в психиатрическом стационаре", "inpatient_psych", "inpatient"),
    "/uslugi/psihiatriya/trevozhnye-i-stressovye-rasstrojstva/": _p("Лечение тревожных и стрессовых расстройств", "лечение тревожных и стрессовых расстройств", "лечения тревожных и стрессовых расстройств", "clinic_topic", "psych_topic", "тревожных расстройствах"),
    "/uslugi/psihiatriya/trevozhnye-i-stressovye-rasstrojstva/panicheskoe/": _p("Лечение панических атак", "лечение панических атак", "лечения панических атак", "clinic_topic", "psych_topic", "панических атаках"),
    "/uslugi/psihiatriya/trevozhnye-i-stressovye-rasstrojstva/okr/": _p("Лечение ОКР", "лечение ОКР", "лечения ОКР", "clinic_topic", "psych_topic", "ОКР"),
    "/uslugi/psihiatriya/trevozhnye-i-stressovye-rasstrojstva/ptsr/": _p("Лечение ПТСР", "лечение ПТСР", "лечения ПТСР", "clinic_topic", "psych_topic", "ПТСР"),
    "/uslugi/psihiatriya/trevozhnye-i-stressovye-rasstrojstva/fobii/": _p("Лечение фобий", "лечение фобий", "лечения фобий", "clinic_topic", "psych_topic", "фобиях"),
    "/uslugi/psihiatriya/trevozhnye-i-stressovye-rasstrojstva/generalizovannoe-trevozhnoe/": _p("Лечение генерализованного тревожного расстройства", "лечение генерализованного тревожного расстройства", "лечения генерализованного тревожного расстройства", "clinic_topic", "psych_topic", "генерализованной тревоге"),
    "/uslugi/psihiatriya/trevozhnye-i-stressovye-rasstrojstva/sociofobiya/": _p("Лечение социофобии", "лечение социофобии", "лечения социофобии", "clinic_topic", "psych_topic", "социофобии"),
    "/uslugi/psihiatriya/trevozhnye-i-stressovye-rasstrojstva/agorafobiya/": _p("Лечение агорафобии", "лечение агорафобии", "лечения агорафобии", "clinic_topic", "psych_topic", "агорафобии"),
    "/uslugi/psihiatriya/trevozhnye-i-stressovye-rasstrojstva/nevroz/": _p("Лечение неврозов", "лечение неврозов", "лечения неврозов", "clinic_topic", "psych_topic", "неврозах"),
    "/uslugi/psihiatriya/rasstrojstva-nastroeniya/": _p("Лечение расстройств настроения", "лечение расстройств настроения", "лечения расстройств настроения", "clinic_topic", "psych_topic", "расстройствах настроения"),
    "/uslugi/psihiatriya/rasstrojstva-nastroeniya/depressiya/": _p("Помощь при депрессии", "помощь при депрессии", "помощи при депрессии", "clinic_topic", "psych_topic", "депрессии"),
    "/uslugi/psihiatriya/rasstrojstva-nastroeniya/bipolyarnoe/": _p("Лечение биполярного расстройства", "лечение биполярного расстройства", "лечения биполярного расстройства", "clinic_topic", "psych_topic", "биполярном расстройстве"),
    "/uslugi/psihiatriya/rasstrojstva-nastroeniya/poslerodovaya-depressiya/": _p("Лечение послеродовой депрессии", "лечение послеродовой депрессии", "лечения послеродовой депрессии", "clinic_topic", "psych_topic", "послеродовой депрессии"),
    "/uslugi/psihiatriya/rasstrojstva-nastroeniya/distimiya/": _p("Лечение дистимии", "лечение дистимии", "лечения дистимии", "clinic_topic", "psych_topic", "дистимии"),
    "/uslugi/psihiatriya/psihoticheskie-rasstrojstva/": _p("Лечение психотических расстройств", "лечение психотических расстройств", "лечения психотических расстройств", "clinic_topic", "psych_topic", "психотических расстройствах"),
    "/uslugi/psihiatriya/psihoticheskie-rasstrojstva/shizofreniya/": _p("Лечение шизофрении", "лечение шизофрении", "лечения шизофрении", "clinic_topic", "psych_topic", "шизофрении"),
    "/uslugi/psihiatriya/psihoticheskie-rasstrojstva/shizoaffektivnoe/": _p("Лечение шизоаффективного расстройства", "лечение шизоаффективного расстройства", "лечения шизоаффективного расстройства", "clinic_topic", "psych_topic", "шизоаффективном расстройстве"),
    "/uslugi/psihiatriya/psihoticheskie-rasstrojstva/shizotipicheskoe/": _p("Лечение шизотипического расстройства", "лечение шизотипического расстройства", "лечения шизотипического расстройства", "clinic_topic", "psych_topic", "шизотипическом расстройстве"),
    "/uslugi/psihiatriya/psihoticheskie-rasstrojstva/psihoz/": _p("Лечение психоза", "лечение психоза", "лечения психоза", "clinic_topic", "psych_topic", "психозе"),
    "/uslugi/psihiatriya/psihoticheskie-rasstrojstva/bredovoe/": _p("Лечение бредового расстройства", "лечение бредового расстройства", "лечения бредового расстройства", "clinic_topic", "psych_topic", "бредовом расстройстве"),
    "/uslugi/psihiatriya/rasstrojstva-lichnosti-i-povedeniya/": _p("Лечение расстройств личности", "лечение расстройств личности", "лечения расстройств личности", "clinic_topic", "psych_topic", "расстройствах личности"),
    "/uslugi/psihiatriya/rasstrojstva-lichnosti-i-povedeniya/pogranichnoe/": _p("Лечение пограничного расстройства личности", "лечение пограничного расстройства личности", "лечения пограничного расстройства личности", "clinic_topic", "psych_topic", "пограничном расстройстве личности"),
    "/uslugi/psihiatriya/rasstrojstva-lichnosti-i-povedeniya/narcissicheskoe/": _p("Лечение нарциссического расстройства личности", "лечение нарциссического расстройства личности", "лечения нарциссического расстройства личности", "clinic_topic", "psych_topic", "нарциссическом расстройстве личности"),
    "/uslugi/psihiatriya/rasstrojstva-lichnosti-i-povedeniya/shizoidnoe/": _p("Лечение шизоидного расстройства личности", "лечение шизоидного расстройства личности", "лечения шизоидного расстройства личности", "clinic_topic", "psych_topic", "шизоидном расстройстве личности"),
    "/uslugi/psihiatriya/rasstrojstva-lichnosti-i-povedeniya/paranoidnoe/": _p("Лечение параноидного расстройства личности", "лечение параноидного расстройства личности", "лечения параноидного расстройства личности", "clinic_topic", "psych_topic", "параноидном расстройстве личности"),
    "/uslugi/psihiatriya/rasstrojstva-lichnosti-i-povedeniya/izbegayushchee/": _p("Лечение избегающего расстройства личности", "лечение избегающего расстройства личности", "лечения избегающего расстройства личности", "clinic_topic", "psych_topic", "избегающем расстройстве личности"),
    "/uslugi/psihiatriya/rasstrojstva-lichnosti-i-povedeniya/zavisimoe/": _p("Лечение зависимого расстройства личности", "лечение зависимого расстройства личности", "лечения зависимого расстройства личности", "clinic_topic", "psych_topic", "зависимом расстройстве личности"),
    "/uslugi/psihiatriya/rasstrojstva-pishchevogo-povedeniya/": _p("Лечение расстройств пищевого поведения", "лечение расстройств пищевого поведения", "лечения расстройств пищевого поведения", "clinic_topic", "psych_topic", "расстройствах пищевого поведения"),
    "/uslugi/psihiatriya/rasstrojstva-pishchevogo-povedeniya/anoreksiya/": _p("Лечение нервной анорексии", "лечение нервной анорексии", "лечения нервной анорексии", "clinic_topic", "psych_topic", "нервной анорексии"),
    "/uslugi/psihiatriya/rasstrojstva-pishchevogo-povedeniya/bulimiya/": _p("Лечение нервной булимии", "лечение нервной булимии", "лечения нервной булимии", "clinic_topic", "psych_topic", "нервной булимии"),
    "/uslugi/psihiatriya/rasstrojstva-pishchevogo-povedeniya/kompulsivnoe-pereedanie/": _p("Лечение компульсивного переедания", "лечение компульсивного переедания", "лечения компульсивного переедания", "clinic_topic", "psych_topic", "компульсивном переедании"),
    "/uslugi/psihiatriya/kognitivnye-i-organicheskie/": _p("Лечение когнитивных и органических расстройств", "лечение когнитивных и органических расстройств", "лечения когнитивных и органических расстройств", "clinic_topic", "psych_topic", "когнитивных расстройствах"),
    "/uslugi/psihiatriya/kognitivnye-i-organicheskie/demenciya/": _p("Лечение деменции", "лечение деменции", "лечения деменции", "clinic_topic", "psych_topic", "деменции"),
    "/uslugi/psihiatriya/kognitivnye-i-organicheskie/alcgejmer/": _p("Лечение болезни Альцгеймера", "лечение болезни Альцгеймера", "лечения болезни Альцгеймера", "clinic_topic", "psych_topic", "болезни Альцгеймера"),
    "/uslugi/psihiatriya/kognitivnye-i-organicheskie/sosudistaya-demenciya/": _p("Лечение сосудистой деменции", "лечение сосудистой деменции", "лечения сосудистой деменции", "clinic_topic", "psych_topic", "сосудистой деменции"),
    "/uslugi/psihiatriya/rasstrojstva-sna/": _p("Лечение расстройств сна", "лечение расстройств сна", "лечения расстройств сна", "clinic_topic", "psych_topic", "расстройствах сна"),
    "/uslugi/psihiatriya/rasstrojstva-sna/bessonnica/": _p("Лечение бессонницы", "лечение бессонницы", "лечения бессонницы", "clinic_topic", "psych_topic", "бессоннице"),
    "/uslugi/psihiatriya/rasstrojstva-sna/narkolepsiya/": _p("Лечение нарколепсии", "лечение нарколепсии", "лечения нарколепсии", "clinic_topic", "psych_topic", "нарколепсии"),
    "/uslugi/psihiatriya/rasstrojstva-sna/lunatizm/": _p("Лечение лунатизма", "лечение лунатизма", "лечения лунатизма", "clinic_topic", "psych_topic", "лунатизме"),
    "/uslugi/psihoterapiya-i-psihologiya/": _p("Психотерапия и психология", "психотерапию и психологию", "психотерапии и психологии", "clinic", "psych"),
    "/uslugi/psihoterapiya-i-psihologiya/psihoterapevt/": _p("Консультация психотерапевта", "консультацию психотерапевта", "консультации психотерапевта", "consult", "psych"),
    "/uslugi/psihoterapiya-i-psihologiya/individualnaya/": _p("Индивидуальная психотерапия", "индивидуальную психотерапию", "индивидуальной психотерапии", "clinic", "psych"),
    "/uslugi/psihoterapiya-i-psihologiya/semejnaya/": _p("Семейная психотерапия", "семейную психотерапию", "семейной психотерапии", "clinic", "psych"),
    "/uslugi/psihoterapiya-i-psihologiya/psiholog/": _p("Консультация психолога", "консультацию психолога", "консультации психолога", "consult", "psych"),
    "/uslugi/psihoterapiya-i-psihologiya/semejnyj-psiholog/": _p("Консультация семейного психолога", "консультацию семейного психолога", "консультации семейного психолога", "consult", "psych"),
}


def phrase_for(service_url: str, service_name: str) -> Phrase:
    found = PHRASES.get(service_url)
    if found is not None:
        return found
    name = service_name or "Услуга"
    return Phrase(name, name, name, "clinic", "treatment")
